.luacheckrc, README.md, lua/typescript-tools/config.lua, lua/typescript-tools/protocol/constants.lua, lua/typescript-tools/protocol/text_document/completion/init.lua, lua/typescript-tools/protocol/text_document/completion/resolve.lua, lua/typescript-tools/protocol/text_document/did_open.lua, lua/typescript-tools/protocol/text_document/inlay_hint.lua, lua/typescript-tools/protocol/utils.lua, tests/requests_spec.lua
resolves #56 
https://github.com/pmizio/typescript-tools.nvim/assets/5601392/4c39ab89-c38b-4d47-acfd-57f76c1f12d4
`tsserver` does not create snippets for functions in the completions list; only upon completion resolve (presumably this is for performance reasons).
`typescript-language-server` deals with this by manually constructing the snippet and tweaking the `inputTextFormat`. We copy that here - as long as `includeCompletionsWithSnippetText = true`.
I chose to do one thing different from`typescript-language-server`: even though we can't put preview all the snippet params in the cmp menu, I still at least add "(...)" so that it visually distinguishes them as snippets. This is especially since [`nvim_cmp` is unable to detect them as …
=> feat: snippet completions for functions

lua/typescript-tools/protocol/text_document/hover.lua, tests/requests_spec.lua
Fixes: https://github.com/pmizio/typescript-tools.nvim/issues/118
=> fix(hover): add correct markdown format to code snippet

README.md
Looks like the link was out of date, and the default options actually live in https://github.com/pmizio/typescript-tools.nvim/blob/master/lua/typescript-tools/config.lua#L17 now.
=> docs: update link to defaults for tsserver ops

lua/typescript-tools/protocol/text_document/completion/init.lua, lua/typescript-tools/protocol/text_document/completion/resolve.lua, lua/typescript-tools/protocol/utils.lua, tests/requests_spec.lua
Contrary to the LSP protocol, we add the snippet insert text at resolve time rather than at list time due to an issue in `tsserver`:
https://github.com/microsoft/TypeScript/issues/51758#issue-1477065873
However, it's only sometimes true that functions need to be snippet-ified at resolve-time. For example, method implementations for subclasses are snippified at list-time, so snippet-ifying them at resolve-time will cause duplication:
https://github.com/pmizio/typescript-tools.nvim/assets/5601392/98f5d655-8068-417a-b10f-4f0253af03d8
note: I also removed the extra $0 at the end of the snippet as that was just blindly copied from `typescript-language-server` but it doesn't add any value.
=> fix: don't snippet-ify function snippets that are already snippet-ified

lua/typescript-tools/rpc.lua
Fixes #156 
[`vim.lsp.rpc.notify()`](https://neovim.io/doc/user/lsp.html#vim.lsp.rpc.notify()) should return `true` when the notification was successfully sent. Without this, [this line](https://github.com/neovim/neovim/blob/6405fa4b117263b92f87b17150abd2d1c6ab5881/runtime/lua/vim/lsp.lua#L1583) is always `nil`, [`LspNotify` autocommands aren't executed](https://github.com/neovim/neovim/blob/6405fa4b117263b92f87b17150abd2d1c6ab5881/runtime/lua/vim/lsp.lua#L1587), and then [inlay hints aren't refreshed](https://github.com/neovim/neovim/blob/6405fa4b117263b92f87b17150abd2d1c6ab5881/runtime/lua/vim/lsp/inlay_hint.lua#L153).
=> fix(rpc): return notification results

README.md, lua/typescript-tools/tsserver_provider.lua
https://github.com/pmizio/typescript-tools.nvim/pull/152 introduced the ability to find `tsserver` based on `mason-registry`.
That approach is problematic because calling `require('mason-registry').get_package(...)` requires `require('mason-registry').refresh` to have been called first.
`mason` works by installing the LSPs into the path, unfortunately though, `tsserver` is just not available yet.
Once https://github.com/mason-org/mason-registry/pull/2845 goes through though, we can do `MasonInstall tsserver`, and voilla, no need to reach into the mason registry.
Leaving this as a draft until the registry PR goes in
@williamboman thanks for the help here!!!
=> feat: find tsserver from path

lua/typescript-tools/capabilities.lua
This boolean condition causes `resolveProvider` to always be true, since `(...) and false` is always false so the stuff on the right side of the `or` will always be used.
=> fix(codelens): correct capability condition

lua/typescript-tools/autocommands/code_lens.lua, lua/typescript-tools/autocommands/common.lua, lua/typescript-tools/utils.lua
Should fix: https://github.com/pmizio/typescript-tools.nvim/issues/173
=> fix: `codelens.refresh` should be called only for supported files

lua/typescript-tools/tsserver_provider.lua
Executable is found but errors pop up inside `Node` ...
Nix tsserver binary is 
```sh
#! /nix/store/lf0wpjrj8yx4gsmw2s3xfl58ixmqk8qa-bash-5.2-p15/bin/bash -e
exec "/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node"  /nix/store/wrif36nqpxiw6f501ln2snyrwbd19k25-typescript-5.2.2/lib/node_modules/typescript/./bin/tsserver "$@" 
```
```
[ERROR][2023-11-16 15:43:26] ...ools/process.lua:184	"process"	"tsserver"	"stderr"	'/nix/store/wrif36nqpxiw6f501ln2snyrwbd19k25-typescript-5.2.2/bin/tsserver:2
exec "/nix/store/5l687mklyr9rhhbvvpvi93zv0zbbi4vg-nodejs-18.18.2/bin/node"  /nix/store/wrif36nqpxiw6f501ln2snyrwbd19k25-typescript-5.2.2/lib/node_modules/typescript/./bin/tsserver "$@" 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected string …
```
=> feat: find global tsserver from Nix store

lua/typescript-tools/autocommands/init.lua, lua/typescript-tools/autocommands/on_attach.lua, lua/typescript-tools/init.lua
as mentioned in the comments of PR #213, the use of a boolean prevents `on_attach` from being called when a new buffer is opened. I tried implementing the same idea of limiting the `on_attach` calls but with buffer number instead.
=> fix: use buffer number instead of a boolean to limit on_attach calls

lua/typescript-tools/api.lua, lua/typescript-tools/protocol/module_mapper.lua, lua/typescript-tools/protocol/text_document/custom_diagnostic.lua, lua/typescript-tools/protocol/text_document/prepare_call_hierarchy.lua, lua/typescript-tools/utils.lua, tests/utils.lua
Fix: https://github.com/pmizio/typescript-tools.nvim/issues/266
This PR will fix not to use the following deprecated api.
- `vim.tbl_add_reverse_lookup()`
- `vim.tbl_islist()`
- `vim.lsp.get_active_clients()`
📝 https://neovim.io/doc/user/deprecated.html#deprecated-0.10
=> fix: deprecated warnings

lua/typescript-tools/protocol/text_document/code_lens/init.lua
In `textDocument/codeLens` handler, `get_parser` has no argument, so it processes with the current buffer content regardless of the textDocument content.
Fixed to respect bufnr as well as `convert_nodes_to_response`.
=> fix: respect bufnr with codelens parser

lua/typescript-tools/protocol/text_document/did_open.lua
According to `:h 'shiftwidth'` if the value is 0 then `tabstop` is used. Currently it will just use 0 as the indent size, this fixes this.
=> fix: properly handle if `shiftwidth = 0`

lua/typescript-tools/autocommands/code_lens.lua
Based on @Chaitanyabsprip comment in #280.
Fixes:
- #280 
- #274 
- #173 
Related PRs:
- #246 
- #177 
---
On a side note, I couldn't make tests work after cloning the repo, here's the output I get:
```
$ make test
nvim --headless --noplugin -u tests/init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.lua'}"
Installing nvim-lua/plenary.nvim
Installing neovim/nvim-lspconfig
Installing nvim-treesitter/nvim-treesitter
Downloading tree-sitter-typescript...
Creating temporary directory
Extracting tree-sitter-typescript...
Compiling...
Treesitter parser for typescript has been installed
Starting...Scheduling: tests//requests_spec.lua
Scheduling: tests//editor_spec.lua
make: *** [test] Error 1
```
=> Fix textDocument/codeLens error when a non-TS file is open

lua/typescript-tools/api.lua
=> fix: fires request_diagnostics only for typescipt client

lua/typescript-tools/protocol/text_document/completion/init.lua
If member completion is triggered with one or more consecutive `s`'s after `.`, the `s`'s will not be deleted, resulting in an incorrect completion.
However, I don't know why the `s*` was included in the pattern, so if there was a good reason for it, please let me know.
Thanks for the great plugin!
https://github.com/user-attachments/assets/cddeb23a-6dcd-4b7d-b337-6176cbe3a686
=> fix: duplicated s on member completion

lua/typescript-tools/capabilities.lua, lua/typescript-tools/integrations.lua, lua/typescript-tools/internal_commands.lua, lua/typescript-tools/protocol/constants.lua, lua/typescript-tools/protocol/text_document/code_action/init.lua, tests/requests_spec.lua
=> feat: implement `Move to file` code action

lua/typescript-tools/tsserver_provider.lua
fixes: #317 
Lsp-config helpers dropped the method `sanitize` in favor of the now provided `vim.fs.normalize`.
Here is the [PR](https://github.com/neovim/nvim-lspconfig/commit/d651732cecfc77be1b3727512bec0438c22410d1#diff-9e30880c16142e9d50a64563fd1260aa9f851b782dd74678163e151b93878568L219) where the function was removed.
=> fix: use vim.fs.normalize instead of using a helper from lspconfig

lua/typescript-tools/protocol/text_document/code_lens/init.lua
Neovim 0.11 changed `query:iter_matches` to return a list of nodes per capture instead of a single `TSNode`. `convert_nodes_to_response` didn’t account for this, causing it to attempt `.range()` on a table, leading to runtime errors.
=> Fix `code_lens` with correct iteration over query match nodes

lua/typescript-tools/config.lua
This PR fixes the deprecated use of the table argument for `vim.validate`. The table argument got deprecated in neovim 0.11 (https://github.com/neovim/neovim/blob/fece4897940896f487559b955e4f8f76d48f299c/runtime/doc/deprecated.txt#L95) and using individual `vim.validate` calls to validate multiple values is recommended now.
This PR has 2 commits:
1. A minimal change that still leverages the table of values to validate and re-implements the previous behavior by calling `vim.validate` in a loop. It has a very small diff
2. Avoids using the table altogether. Refactors the code to call `vim.valdiate` for each value to validate, without the loop.
Feel free to drop the 2nd one if you think the 1st one is good enough and having a single table of values to validate is convenient.
By the way, …
=> fix: deprecated table argument for `vim.validate`

lua/typescript-tools/protocol/text_document/document_highlight.lua, lua/typescript-tools/protocol/text_document/document_symbol.lua, lua/typescript-tools/protocol/text_document/hover.lua, lua/typescript-tools/protocol/text_document/signature_help.lua, lua/typescript-tools/tsserver.lua
Fixes #321
The errors from the coroutines used to execute the handlers where previously ignored, this PR makes them noisy and writes them to the general lsp log with a full stacktrace to allow users to give better error reports.
This also surfaced 2 errors in my short tests, a missing early return for the documentHighlight handler and a similar error for the hover handler (that was the cause for #321). Both errors are fixed now.
=> fix: gracefully handle `handlers`  errors and fix documentHighlight and hover errors

lua/typescript-tools/protocol/text_document/code_action/resolve.lua
Fixes an error similar to the ones found on #346, this is what `:LspLog` contained
```log
[ERROR][2025-04-22 11:36:06] ...ols/tsserver.lua:104	"tsserver"	"Unexpected error while handling response: "	"codeAction/resolve"
[ERROR][2025-04-22 11:36:06] ...ols/tsserver.lua:105	"tsserver"	"...cript-tools.nvim/lua/typescript-tools/protocol/utils.lua:135: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
[C]: in function 'ipairs'
...cript-tools.nvim/lua/typescript-tools/protocol/utils.lua:135: in function 'get_edits'
...ipt-tools/protocol/text_document/code_action/resolve.lua:60: in function <...ipt-tools/protocol/text_document/code_action/resolve.lua:18>"
```
The response that caused the error looks like
```lua
M.handler body: {
command = "getEditsForRefactor",
message = …
```
=> fix: send empty response if code_action/resolve fails
