pmizio/typescript-tools.nvim

lua/typescript-tools/init.lua

Fix setting lspconfig's config multiple times

---

lua/typescript-tools/tsserver_provider.lua

Fixes https://github.com/pmizio/typescript-tools.nvim/issues/50

fix: resolve global tsserver using `npm root -g`

---

lua/typescript-tools/tsserver_provider.lua

Possibly fixes: https://github.com/pmizio/typescript-tools.nvim/issues/60

feat: additional step in tsserver path resolve strategy

---

lua/typescript-tools/protocol/workspace/symbol.lua

Fixes: https://github.com/pmizio/typescript-tools.nvim/issues/72

fix(workspace/symbol): performance by request correction

---

README.md
lua/typescript-tools/config.lua
lua/typescript-tools/process.lua

Fixes: https://github.com/pmizio/typescript-tools.nvim/issues/65

feat(process): pass max memory limit to tsserver

---

lua/typescript-tools/protocol/text_document/code_action/init.lua
lua/typescript-tools/protocol/utils.lua

This PR enables action called `Move to a new file`

fix: move refactor

---

README.md
lua/typescript-tools/api.lua

Add filter_diagnostics helper

---

lua/typescript-tools/tsserver_provider.lua
lua/typescript-tools/utils.lua

Possible fix for: https://github.com/pmizio/typescript-tools.nvim/issues/88

fix(tsserver provider): recursive search performance

---

lua/typescript-tools/init.lua
lua/typescript-tools/tsserver.lua
lua/typescript-tools/tsserver_provider.lua

fixes: https://github.com/pmizio/typescript-tools.nvim/issues/88

feat: introduce asynchronous startup for plugin

---

lua/typescript-tools/protocol/text_document/code_action/batch/init.lua
lua/typescript-tools/protocol/text_document/code_action/init.lua
lua/typescript-tools/protocol/workspace/will_rename_files.lua
lua/typescript-tools/request_queue.lua
lua/typescript-tools/tsserver.lua
lua/typescript-tools/types.lua

Fixes: https://github.com/pmizio/typescript-tools.nvim/issues/109

fix(cancelling): assign numeric ids for combined requests

---

lua/typescript-tools/api.lua
lua/typescript-tools/protocol/text_document/code_action/batch/init.lua

Fixes: https://github.com/pmizio/typescript-tools.nvim/issues/111

fix(batch actions): skip tsserver request when there is no fixable error

---

lua/typescript-tools/protocol/text_document/code_action/batch/init.lua

fix: fix missing imports bug

---

README.md
lua/typescript-tools/api.lua
lua/typescript-tools/config.lua
lua/typescript-tools/protocol/text_document/code_action/init.lua
lua/typescript-tools/user_commands.lua

fix: remove unused imports code action

---

lua/typescript-tools/protocol/text_document/code_action/init.lua

fix: adds new refactoring

---

README.md
lua/typescript-tools/api.lua
lua/typescript-tools/async.lua
lua/typescript-tools/user_commands.lua
lua/typescript-tools/utils.lua

Closes: https://github.com/pmizio/typescript-tools.nvim/issues/94

feat: implement `TSToolsRenameFile` command

---

lua/typescript-tools/protocol/text_document/completion/resolve.lua

Fixes: https://github.com/pmizio/typescript-tools.nvim/issues/171

fix: snippet tabstop indexes

---

.github/workflows/lint-commits.yml
.github/workflows/lint.yml
README.md
lua/typescript-tools/config.lua
lua/typescript-tools/process.lua

Closes: https://github.com/pmizio/typescript-tools.nvim/issues/180

feat: add option to customize tsserver locale

---

lua/typescript-tools/protocol/text_document/definition.lua
lua/typescript-tools/tsserver_provider.lua

Fixes issues related to https://github.com/pmizio/typescript-tools.nvim/issues/192.
Adds support for Yarn's Plug n Play features.

Feat Yarn PnP

---

lua/typescript-tools/protocol/text_document/custom_diagnostic.lua

fix(diagnostic): fixed list of error codes should be warnings

---

lua/typescript-tools/protocol/text_document/folding_range.lua

fix: add nil assertion for folding ranges

---

lua/typescript-tools/init.lua

fix: `on_attach` called multiple times with `separate_diagnostic_server`

---

lua/typescript-tools/protocol/text_document/semantic_tokens.lua

fix: fixes semantic tokens for @vue/typescript-plugin

---

lua/typescript-tools/protocol/text_document/prepare_call_hierarchy.lua

fix: prepare call hierarchy failed calls

---

lua/typescript-tools/rpc.lua
lua/typescript-tools/types.lua
lua/typescript-tools/utils.lua

fix: fixes LspRestart command on nightly

---

lua/typescript-tools/autocommands/common.lua
lua/typescript-tools/autocommands/diagnostics.lua

fix: fixes diagnostics for vue

---

lua/typescript-tools/protocol/text_document/semantic_tokens.lua

fix: removes _str_utfindex_enc in nightly

---

lua/typescript-tools/api.lua

fix: file references

---

lua/typescript-tools/config.lua

fix: config check for nvim below 0.11

---

lua/typescript-tools/api.lua
lua/typescript-tools/utils.lua

fix: go to source definition

---

lua/typescript-tools/internal_commands.lua

fix: exposed code actions
